CREATE TABLE [dbo].[Aluno](
	[Ra] [bigint] NOT NULL,
	[Cpf] [bigint] NOT NULL,
 CONSTRAINT [PK_Aluno] PRIMARY KEY CLUSTERED 
(
	[Ra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Aluno]  WITH CHECK ADD  CONSTRAINT [FK_Aluno_Usuario] FOREIGN KEY([Cpf])
REFERENCES [dbo].[Usuario] ([Cpf])
GO

ALTER TABLE [dbo].[Aluno] CHECK CONSTRAINT [FK_Aluno_Usuario]
GO


