CREATE TABLE [dbo].[Professor](
	[CodFuncionario] [bigint] NOT NULL,
	[Cpf] [bigint] NOT NULL,
 CONSTRAINT [PK_Professor] PRIMARY KEY CLUSTERED 
(
	[CodFuncionario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Professor]  WITH CHECK ADD  CONSTRAINT [FK_Professor_Usuario] FOREIGN KEY([Cpf])
REFERENCES [dbo].[Usuario] ([Cpf])
GO

ALTER TABLE [dbo].[Professor] CHECK CONSTRAINT [FK_Professor_Usuario]
GO


